
/*if(!ds_map_exists(global.text_setted,"event_30"))
{
	text_id="event_30";
	set_event=true;
}
if(ds_map_exists(global.text_setted,"event_30")&&!ds_map_exists(global.text_setted,"event_32"))
{
	text_id="talk_2_9";
}
if(ds_map_exists(global.text_setted,"event_30")&&Obj_Player.set_remove_number==1)
{
	text_id="event_34";
	set_event=true;
}
if(ds_map_exists(global.text_setted,"event_34"))
{
	text_id="talk_10"
}